baseurl: "https://justinyang.me"
languageCode: "en-us"
title: "MINDSET: Multimodal INference and Data science for pSychiatric Epidemiology and Treatment"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  presentations: "/presentations/:year/:month/:day/:title/"

menu:
  main:
    - name: About
      url: "/"
      weight: 1
    # - name: Team
    #   url: "team/"
    #   weight: 2
    - name: Publications
      url: "publications/"
      weight: 3
    - name: Funding
      url: "funding/"
      weight: 4
    - name: Presentations
      url: "presentations/"
      weight: 5
    - name: Teaching
      url: "teaching/"
      weight: 6
    - name: Service
      url: "service/"
      weight: 7
    - name: Contact
      url: "contact/"
      weight: 8

params:
  description: "MINDSET: Multimodal INference and Data science for pSychiatric Epidemiology and Treatment"
  footer: "Published using [blogdown](https://bookdown.org/yihui/blogdown) and [Hugo](https://gohugo.io) <br> &copy; [Justin C Yang](https://justinyang.me) 2019-{Year}"
  githubSource: "https://github.com/yangjustinc/yangjustinc-blogdown/blob/main/content/"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
      
  env:
    ORCID_TOKEN: "a273e212-bcdf-4131-b60b-54317eab2910"
